[workspace]
members = ["daemon", "library"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
android_logger = "0.15"
anyhow = "1"
ctor = "0.6"
env_logger = "0.11"
log = "0.4"
memfd = "0.6"
nix = { version = "0.31" }
once_map = "0.4"
procfs = "0.18"
r3solvr = { git = "https://github.com/Mufanc/r3solvr" }
scopeguard = "1.2"
syscalls = "0.8"
wisp = { git = "https://github.com/Mufanc/wisp" }
